//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 09:19:48 AM EET 
//


package com.github.hi_fi.statusupdater.qc.infrastructure;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entities }
     * 
     * @return Entities instance of {@link Entities }
     */
    public Entities createEntities() {
        return new Entities();
    }

    /**
     * Create an instance of {@link Entities.Entity }
     * 
     * @return Entity an instance of {@link Entities.Entity }
     */
    public Entities.Entity createEntitiesEntity() {
        return new Entities.Entity();
    }

    /**
     * Create an instance of {@link Entities.Entity.Fields }
     * 
     * @return Fields an instance of {@link Entities.Entity.Fields }
     */
    public Entities.Entity.Fields createEntitiesEntityFields() {
        return new Entities.Entity.Fields();
    }

    /**
     * Create an instance of {@link Entities.Entity.Fields.Field }
     * 
     * @return Field an instance of {@link Entities.Entity.Fields.Field } 
     */
    public Entities.Entity.Fields.Field createEntitiesEntityFieldsField() {
        return new Entities.Entity.Fields.Field();
    }

}
